name: mbtiles_example
description: Example program for the mbtiles package
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  mbtiles: { path: ../ }
  path: ^1.8.3

dev_dependencies:
  lint: ^2.1.0